name: Run Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write
  actions: write
  pull-requests: write

jobs:
  test:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
    
    - name: Setup DB
      run: docker compose up -d

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew test

    - name: List test results for debug
      run: ls -R build

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'

    - name: Notifications for Discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      env:
       DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
       status: ${{ job.status }}
